name: SiegeWar
main: team.siegewar.SiegeWar
version: 0.1 alpha
authors: [a_austin,nodak_lzc]
commands:
  siegewar:
    description: ¹¥³ÇÕ½ÕùÃüÁî
    usage: /siegewar help
    aliases: [sw,siegew]